FROM python:3.5.1-alpine

COPY ./requirements.txt /src/requirements.txt
COPY ./dev-requirements.txt /src/dev-requirements.txt

RUN cd /src && pip install -r requirements.txt
RUN cd /src && pip install -r dev-requirements.txt

COPY . /src

WORKDIR /src

CMD ["python", "-u", "./app.py", "--debug"]
